# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'SlidePhoto' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SlidePhoto
  pod 'SnapKit'
  pod 'HandyJSON'
  pod 'SDWebImage'
  

end
